#
# Module manifest for module 'wingetposh'
#
# Generated by: yvesg
#
# Generated on: 20-11-22
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'wingetposh.psm1'

# Version number of this module.
ModuleVersion = '0.8.0'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = 'f1f782ec-e131-4e03-b909-8a60e5aeb49b'

# Author of this module
Author = 'yvesg'

# Company or vendor of this module
CompanyName = 'Unknown'

# Copyright statement for this module
Copyright = '(c) yvesg. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Helpers functions for Winget'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
#RequiredModules = @('Microsoft.PowerShell.ConsoleGuiTools')

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
ScriptsToProcess = @('./wingetLocals.ps1')

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @('Get-WGPackage', 'Invoke-Winget', 'Out-Object', 'Search-WGPackage')

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = @(
    'wingetposh.psd1'
    'wingetposh.psm1',
    'wingetLocals.ps1'
)

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('winget','helper','powershell', 'TUI')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/Yves848/WingetPosh/blob/master/licence.txt'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/Yves848/WingetPosh'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = '0.5.1 : 
        - Fixed the show-WGList bug when there is no updatable packages to show.
        0.5.2 : 
        - Removed the "-Interactive" switch to search-WGPackage.       
        - Removed the search parameter from search-WGPackage.
        - Allowing multiple selection in uninstall-WGPackage.
        - Removing crash brug when no package is found in search-WGPackage.
        - Removing the "-Interactive" switch to updage-WGPackage.  If no Object is passed through the pipeline, it will automatically display an interactive grid
        - Update readme.md
        
        0.5.4 : 
        - Addind a license file.

        0.5.5 : 
        - Adding licence acceptance.
        
        0.5.6 : 
        - Adding headless functions : Get-WGList and Get-WGUpdatables

        0.6.0 :
        - Removing "Microsoft.PowerShell.ConsoleGuiTools" dependance to add Powershell 5.1 compatibility
        - Rewriting the TUI in full powershell (some flickering still to fix)
        - Adding "Invoke-Winget" funtion to add generic call to Winget
        
        0.6.1 : 
        - Fix -Install switch of Install-WGPAckage
        - Rename Show-WGUpdatables to Update-WGPackages
        - Add a switch -Update to Update-WGPackages

        0.6.2 :
        - Fix flickering
        - rename Update-WGPackages to Update-WGPackage for uniformity
        - in Install-WGPackage, F3 allows to run a new search
        - Version of the module shown in the window frame
        
        0.6.3 : 
        - remove the module version of the window frame
        
        0.6.4 :
        - Add "+" and "-" keys for selections in the grid
        - Version of the module shown in the window frame (back)
        - add "?" to display help
        
        0.6.5 :
        - changing visuals, refining windows drawing
        - add a "package" parameter to Install-WGPackage
        
        0.6.6 :
        - Correctiong bugs in install, uninstall and update functions
        - Fixing the order of the install-WGPackage parameters

        0.7.0 :
        - Changing search mode.  Now the search is on everything, not only the name
        - Improving winget result parsing
        - Every function now returns a hastable.  Faster, lighter
        - Adding a "Out-Object" function to convert hashtable results in PsCustomObject arrays (if needed)
        - Adding a "Search-WGPackage" to search without the graphical interface
        
        0.7.2 : 
        - Minor bug fixes
        
        0.7.3 :
        - fixing visual function (using hastables)
        
        0.7.4 :
        - fixing bug with visual functions returning multiple objects
        
        0.7.5 :
        - Fixing the update-wgpackage when multiple packages selected
        
        0.7.9 :
        - Start Using runspaces to multitask the module.
          First usage is for animating the waitings.
          Last version before heavy code restucture / rewrite
        - Small visual improvements
        
        0.8.0 : 
        - .......'

        
        # Prerelease string of this module
        Prerelease = 'beta'

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        RequireLicenseAcceptance = $true

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

